TACOSTRAT-1526  _elements Parameter Selection
projecttacoma/bulk-export-app pull request #10
Opened 2024-07-19 20:48 UTC by cgolemme

# Summary

This PR adds the functionality to select elements that the user wants to include in the `_elements` parameter of the bulk export request. There are two ways to add parameters. The first way is to select a type and then select a number of elements that you want to export on that resource type. The other way is to select and element that will apply to all resource types on the server.

[JIRA Issue](https://jira.mitre.org/browse/TACOSTRAT-1526)

## New behavior

The  elements tab of the parameters section of the query-builder page is now implemented. The page has two multiselect input fields. 

The bottom one is a standard input field that is similar to the one on the type tab of this page where the user can select any number of elements, add, remove, or remove all elements. It is searchable and the selected options disappear from the dropdown and are shown in the input box at the top. This input is used for element filters that the user wants to apply to all resource types that are exported. Adding `id` for example is equivalent to adding a `_element=id` to the query string of the bulk export request.

The top input is more complicated. The user first selected a type they want to add element fitlers to. When the user selects a type, a modal is opened that prompts them to select elements in a dropdown similar to the one described above. Each type as some mandatory elements that are specified by the fhir spec. These mandatory elements are sourced from the `fhir-spec-tools` repo and currently come from `mandatoryElements.tsx` file in `src/data`. The mandatory elements for each type are displayed in a box inside their respective modal when the user opens it. They also appear as disabled fields in the dropdown with tooltips that tell the user why they are disabled.

When the user selects a type and then elements on that type to filter for, the value is displayed in the input box like `Condition: id, name`. The user can clear all by clicking the icon on the right, clear individual types by clicking the x next to the type, or edit active type element filters by searching the resource type name in the input and clicking on option in the dropdown.

All of the actions described above actively change the export request string shown at the top of the page. When the user executes the workflow to view the output, the element filtering feature should be actively reflected in the returned files.

## Code changes

# Testing guidance
- run `npm run check`
- Check that prettier and eslint cause no errors
- Check that all the tests pass
- Test endpoints on Insomnia

2024-07-25 14:34 UTC, elsaperelli requested changes
Incredible job on the UI and functionality of this! Just some code organization comments and one UI comment!

I noticed that if the user adds a TON of elements, then the query string gets super long. Besides the copy button, I don't think there is a way for the user to view the full string if it is longer than the box (correct me if I am wrong). I think a way to view the full string somehow would be beneficial! (tooltip, popover, etc.)
![image](https://github.com/user-attachments/assets/c3b6e9db-aa0e-42b9-90f3-021f0fd6009f)

2024-07-25 14:34 UTC, elsaperelli commented on data/supportedElements.ts
> +export const supportedElements = PropertyPaths.parsedPropertyPaths;
Honestly, I am not sure we need a file for these (`mandatoryElements`, `supportedElements`, and `supportedResources`). I would just import them in the files where they are used!

2024-07-25 14:34 UTC, elsaperelli commented on src/components/export-execution/requested-files.tsx
> +          </Center>
I like this if/when we implement download all files so make sure you make note of it but I think for now we should remove it. I definitely try my best to stay away from adding components that we aren't 1000% sure we are going to implement so that way if it just doesn't happen we don't need to take it out later.

2024-07-25 14:34 UTC, elsaperelli commented on src/state/element-params-state.ts
> + * Recoil state to manage the Type Parameters for the export request.
Do you mean element parameters?

2024-07-25 14:34 UTC, elsaperelli commented on src/components/parameter-pages/elements-modal.tsx
> +function MandatoryElementList({ resourceType }: { resourceType: string }) {
I think this could be a good opportunity for you to do a little bit of research into some coding best practices (mostly because I am not totally sure lol). I am not super into the idea of having multiple functions in this file when we have seemingly just had one per component file (I could be wrong). Not sure if this is ideal or not and if not, what is the ideal? Do we put these other components into their own file? Or do we try to combine these? It's ok if the conclusion ends up being that this is fine I just am curious.

2024-07-25 14:34 UTC, elsaperelli commented on src/components/parameter-pages/elements-modal.tsx
> +function createComboBoxData(resourceType: string) {
Since this is returning an array (not a React component), then I would put this in a util file

2024-07-25 14:34 UTC, elsaperelli commented on src/util/exportRequestBuilder.ts
> +  queryParams: BuilderRequestQueryParams;
```suggestion
  queryParams: BuilderRequestQueryParams;
  id?: string;
```
I think putting the optional ones at the end is good practice

2024-07-25 14:34 UTC, elsaperelli commented on src/util/exportRequestBuilder.ts
> +
I think this file has a few too many very small functions that are only used in one place. For example, `typeElementToString` just converts an object to a string and is only used in `buildElementsQueryString`. Unless you foresee using `typeElementToString` in other places, I would just move that line into `buildElementsQueryString`. See if you can consolidate other things in this file that make sense. I have a hard time with when to split things up but I think sometimes splitting up things TOO much can hinder code readability. It is certainly a delicate balance but I try to keep things together and only pull things out when they are going to be reused.

2024-07-25 17:26 UTC, cgolemme commented on src/components/parameter-pages/elements-modal.tsx
> +function MandatoryElementList({ resourceType }: { resourceType: string }) {
I think i will probably reuse this for the type filters, so I moved it to its own file.

2024-07-27 16:43 UTC, elsaperelli requested changes
Two very nitpicky comments otherwise looks great! Since this introduces a lot of changes, I would love if @hossenlopp or @lmd59 could take even a super quick look so I will hold off on merging for now.

2024-07-27 16:43 UTC, elsaperelli commented on src/util/exportRequestBuilder.ts
> +  const queryString = buildQueryString(queryParams) ?? '';
```suggestion
  const { baseUrl, exportType, id, queryParams } = request;
  const exportPath = buildExportPath(exportType, id);
  const queryString = buildQueryString(queryParams) ?? '';
```
Lol I have such a hard time deciding how much white space is too much...I feel like this makes a bit more sense and matches the general vibe of the rest of the file. Nitpicky but it was something I immediately noticed

2024-07-27 16:43 UTC, elsaperelli commented on src/util/multiselectUtil.ts
> +export { createComboBoxData, resourceTypesDropdownData, allSupportedElements };
I would just export these in their definitions like you did in `exportRequestBuilder.ts`.

2024-07-29 19:38 UTC, elsaperelli approved these changes
🥳

2024-07-31 20:40 UTC, hossenlopp approved these changes
This works pretty well!

2024-07-31 20:40 UTC, merged