Patient Dropdown Data Population and Refactor
projecttacoma/bulk-export-app pull request #2
Opened 2024-06-19 15:20 UTC by cgolemme

# Summary

This PR adds patient data from the bulk export server to the dropdown select box on the Patient Export card. Before, it was filled with fake data because the `/Patient` endpoint was not yet implemented on the bulk export server. 

Additionally, This PR refactors data fetching from `/Patient` and `/Group` endpoints of the bulk-data-server. This PR also refactors, the `export-type` component in order to follow best practices with the `useEffect` hook.

Also moved components associated with the query selector page into new folder inside components folder.

## New behavior

Patient dropdown data is now populated from the bulk-export-server. With this change, I also moved the data fetching for both the patient dropdown and the group dropdown to the top level page component, and passed the fetched data down to the `export-type` component. This allowed me to use built in `next.js` server side data fetching, which is preferred for something like populating a dropdown.

The ExportType component is now more streamlined. Instead of passing the react state value and setter function to its child components, `BuildQueryButton` and `Dropdown`, I moved the dropdown components to be in the ExportType component. This allows us to minimize the `useEffect` hook usage, which is best react practice. Also, now just the react state value is passed to BuildQuery button.

The BuildQueryButton component is now more succinct and readable (I think). I moved the conditions for the tooltip and disabled button to the top of the file for readability and combined the "system" and "patient"/"group" branches of this component as much as possible.

## Code changes

- `/src/app/layout.tsx` changed the metadata description to be a little better.
- `/src/app/page.module.css` removed some unused styles.
- `/src/app/query-selector/layout.tsx`:  removed the 'use client' in order to use async functions on the `page.tsx` file. Because of this change, I had to import Mantine components like the `Appshell.Header` directly (because of some strange mantine reason). Changed Text from `a` component to next `Link` component to follow best practices.
- `/src/app/query-builder/page.tsx`: added functions to get data for dropdowns asynchronously and changed the page to render this data.
- `/src/app/query-builder/page.modules.css`: small style changes and removed unused ones.
- `/src/components/export-type.tsx` refactor and rename props.
-  `/src/components/build-query-button.tsx` refactor.
- `/src/components/dropdown.tsx` deleted and functionality moved into `export-type.tsx`.

# Testing guidance
- Start the bulk data server instructions [here](https://github.com/projecttacoma/bulk-export-server)
- `npm run check`
- `npm run dev`
- Go to http://localhost:3001/
- Navigate to query selector page
- Try selecting an id from the dropdown and click the button. Verify that the data on the next page is the selected data.
- Try selecting an id from both dropdowns and clicking the button on one of them. Make sure that the type of the export is correct.
- Verify that the button cannot be pressed if there is not a element selected, and that the tooltip appears.

2024-06-24 18:36 UTC, elsaperelli requested changes
Just a few small comments but overall functionality looks great!

2024-06-24 18:36 UTC, elsaperelli commented on src/components/query-selector/export-type.tsx
> +}
At some point (not necessary right now) we may be using these more and may want to pull them out in a types file

2024-06-24 18:36 UTC, elsaperelli commented on src/components/query-selector/export-type.tsx
> +          {exportType == 'system' ? (
You can make this slightly more consider by using `??`! That allows you basically just to say "if" and have no "else". So you would do `{exportType == 'system' ?? (<Select ...`

2024-06-24 18:36 UTC, elsaperelli commented on src/components/query-selector/build-query-button.tsx
> +  const toolTipDisabled = exportType === 'system' ? true : queryId ? true : false;
This certainly works but I can't help but wonder if there is some and/or logic that could make this slightly more readable LOL. You could do `toolTipEnabled`

2024-06-24 18:36 UTC, elsaperelli commented on src/components/query-selector/export-type.tsx
> +          {exportType == 'system' ? (
Oh also `===` instead of `==`

2024-06-24 18:36 UTC, elsaperelli commented on src/components/query-selector/export-type.tsx
> +  const [queryId, setQueryId] = useState<string | null>('');
I think we either want to just make this type a string or initialize it as null? https://gist.github.com/mgramigna/bdc933fae2150216681c28d1f0f7aac7#hooks

2024-06-24 19:25 UTC, cgolemme commented on src/components/query-selector/build-query-button.tsx
> +  const toolTipDisabled = exportType === 'system' ? true : queryId ? true : false;
Lol I kind of just extracted the operators I had in the components. I found a better way to do this.

2024-06-24 21:06 UTC, elsaperelli requested changes

2024-06-24 21:06 UTC, elsaperelli commented on src/components/query-selector/build-query-button.tsx
> +  const buttonEnabled = exportType === 'system' || queryId != null;
```suggestion
  const buttonEnabled = exportType === 'system' || queryId !== null;
```

2024-06-25 15:24 UTC, elsaperelli approved these changes
Lgtm!

2024-06-25 20:04 UTC, merged